apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-nginx
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: site-nginx
  template:
    metadata:
      labels:
        app: site-nginx
    spec:
      containers:
      - image: nakabonne/sha-0802a17
        name: site-nginx
        ports:
        - containerPort: 80
